name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chesslib-python3:$GITHUB_SHA
    
  test:
    
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Run the unit tests
      run: docker run chesslib-python3:$GITHUB_SHA python3 test.py
